AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template for SSP Helper web app
Resources:

  BylawsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Year
          AttributeType: N
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: Year
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Bylaws

  BylawsInfoReaderLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      RoleName: BylawsInfoReaderLambdaRole


  BylawsInfoReaderLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: BylawsInfoReaderLambda
      Handler: index.lambda_handler
      Role: !GetAtt BylawsInfoReaderLambdaRole.Arn
      Runtime: python3.7
      Code:
        ZipFile: |
%BylawsInfoReaderPlaceholder%
